version: '3.8'
services:
  app:
    build: .
    ports:
      - 8000:8000
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=vhost
    ports:
      - 15672:15672
